---
name: Terraform Deployments Azure
on:
  push:
    branches:
      - main
      - release/*
  workflow_dispatch: null
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout source code
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: 1.6.6

      - name: Terraform Fmt
        id: fmt
        run: terraform fmt -check    
        
      - name: Terraform Init
        id: init
        run: terraform init
          -backend-config="storage_account_name=${{  vars.STORAGE_ACCOUNT }}"
          -backend-config="container_name=${{ vars.CONTAINER_NAME }}"
          -backend-config="resource_group_name=${{ vars.RESOURCE_GROUP }}"

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color 

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color   
