---
name: Terraform Deployments Azure
on:
  push:
    branches:
      - main
      - release/*
  workflow_dispatch: null
jobs:
  Build and Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a sample github action
        run: echo "this workflow run successfully for this particular actions"
      # - name: Setup TFLint
      # - uses: terraform-linters/setup-tflint@v4.0.0
      #   with:
      #     tflint_version: null
      #     github_token: null
      #     tflint_wrapper: null
