---
name: Terraform Deployments Azure
on:
  push:
    branches:
      - main
      - release/*
  workflow_dispatch: 
  
jobs:
  Build:
    name: "Terraform Dev"
    env:
      ARM_CLIENT_ID: ${{ secrets. ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets. ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets. ARM_SUBSCRIPTION_ID }}
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        shell: bash
          
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: 'Terraform Format'  
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.14.8
        tf_actions_subcommand: 'fmt'
        tf_actions_working_dir: './terraform'

    - name: 'Terraform Init'  
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.14.8
        tf_actions_subcommand: 'init'
        tf_actions_working_dir: './terraform'
   
    
    - name: 'Terraform Validate'  
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.14.8
        tf_actions_subcommand: 'validate'
        tf_actions_working_dir: './terraform'

    - name: 'Terraform Plan'  
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.14.8
        tf_actions_subcommand: 'plan'
        tf_actions_working_dir: './terraform'    
     
