---
name: Terraform Deployments Azure
on:
  push:
    branches:
      - main
      - release/*
  workflow_dispatch: 
  
jobs:
  Build:
    name: "Terraform Dev"
    environment: dev
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform/environments
    steps:
      - uses: actions/checkout@v4
        name: Checkout source code
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6
    
        
      - name: Terraform Init
        id: init
        run: terraform init
          -backend-config="storage_account_name=${{  vars.STORAGE_ACCOUNT }}"
          -backend-config="container_name=${{ vars.CONTAINER_NAME }}"
          -backend-config="resource_group_name=${{ vars.RESOURCE_GROUP }}"

      - name: Terraform Fmt
        id: fmt
        run: terraform fmt -check        

      - name: Terraform Validate
        id: validate
        run: terraform validate  

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan  -input=false
          working-directory: ./terraform/environments

      # - name: Terraform Apply
      #   run: terraform apply -auto-approve  -input=false
