---
name: Terraform Deployments Azure
on:
  push:
    branches:
      - main
      - release/*
  workflow_dispatch: null
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout source code
        
      - uses: azure/login@v2
        name: azure login
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        
